<?php

/**
 * @file
 * Class for handling Github requests.
 */

// Common functions.
e107_require_once(e_PLUGIN . 'e107projects/includes/e107projects.common.php');
// This file is generated by Composer.
e107_require_once(e_PLUGIN . 'e107projects/vendor/autoload.php');

// TODO - use Redis cache server?
// use Cache\Adapter\Redis\RedisCachePool;
use \Github\Client as GithubClient;
use \Github\ResultPager;

/**
 * Class e107projectsGithub.
 */
class e107projectsGithub
{

	/**
	 * Plugin preferences.
	 *
	 * @var
	 */
	private $plugPrefs;

	/**
	 * @var GithubClient
	 */
	private $client;

	private $paginator;

	/**
	 * Constructor.
	 */
	public function __construct()
	{
		$social_login = e107::getConfig()->get('social_login');
		$client_id = varset($social_login['Github']['keys']['id'], '');
		$secret = varset($social_login['Github']['keys']['secret'], '');
		
		$this->plugPrefs = e107::getPlugConfig('e107projects')->getPref();
		$this->client = new GithubClient();
		$this->client->authenticate($client_id, $secret, Github\Client::AUTH_URL_CLIENT_ID);
		$this->paginator = new ResultPager($this->client);
	}

	/**
	 * Get Github username by e107 user ID.
	 *
	 * @param int $user_id
	 *  User ID in e107.
	 *
	 * @return string|boolean
	 */
	public function getGithubUsernameByUserID($user_id = USERID)
	{
		$user = e107::user($user_id);
		$userXUP = varset($user['user_xup'], '');
		list($provider, $githubID) = explode('_', $userXUP);

		if(!is_numeric($githubID))
		{
			return false;
		}

		$url = 'https://api.github.com/user/' . $githubID;
		$response = e107projects_http_request($url);

		if(empty($response->error))
		{
			$data = json_decode($response->data);
			return varset($data->login, false);
		}

		return false;
	}

	/**
	 * Get the repositories of a user.
	 *
	 * @link http://developer.github.com/v3/repos/
	 *
	 * @param string $username
	 *  The username.
	 * @param string $type
	 *  Role in the repository.
	 * @param string $sort
	 *  Sort by.
	 * @param string $direction
	 *  Direction of sort, asc or desc.
	 *
	 * @return array|boolean
	 *  List of the user repositories, or false.
	 */
	public function getUserRepositories($username, $type = 'owner', $sort = 'full_name', $direction = 'asc')
	{
		if(empty($username))
		{
			return false;
		}

		$userAPI = $this->client->api('user');
		return $this->paginator->fetchAll($userAPI, 'repositories', array($username, $type, $sort, $direction));
	}

}
